# Generated by Django 5.0.4 on 2024-05-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerformstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContractorFormStatus',
        ),
        migrations.DeleteModel(
            name='CustomerFormStatus',
        ),
    ]
